### ISSUE TITLE
decide on approach for integrating into each project

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-log#7]
next we need to decide on the approach we're going to use to integrate logging into each workstation subcomponent. @rmol suggested that it might be easier to write a syslog plugin. This ticket is for timeboxed prototyping of that approach. 

Once we take a crack at it, if it seems promising, then we can integrate that instead of this [logging.StreamHandler](https://github.com/freedomofpress/securedrop-log/blob/master/securedrop_log/__init__.py#L38)-based method.

**Comment by eloquence** [comment]
https://github.com/freedomofpress/securedrop-log/pull/8 is the way to go, closing this one.
